# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DocsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('css', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('js', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('templates', 'templates'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('top.html', 'top.html')], default='', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('css', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('js', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('templates', 'templates'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('top.html', 'top.html')], default='', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('css', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('js', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('templates', 'templates'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('top.html', 'top.html')], default='', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('css', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('js', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('templates', 'templates'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('top.html', 'top.html')], default='', max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GreenPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('css', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('js', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('templates', 'templates'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('top.html', 'top.html')], default='', max_length=255, null=True)),
                ('caption', tinymce.models.HTMLField()),
                ('free_delivery_button', models.ImageField(upload_to='')),
                ('no_delivery_button', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HowPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('css', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('js', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('templates', 'templates'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('top.html', 'top.html')], default='', max_length=255, null=True)),
                ('caption', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MintPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('css', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('js', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('templates', 'templates'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('top.html', 'top.html')], default='', max_length=255, null=True)),
                ('left_image', models.ImageField(upload_to='')),
                ('right_image', models.ImageField(upload_to='')),
                ('caption', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrangePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('css', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('js', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('templates', 'templates'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('top.html', 'top.html')], default='', max_length=255, null=True)),
                ('items', models.ManyToManyField(to='base.ImageItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TextDoubleImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('subimage', models.ImageField(upload_to='')),
                ('text', tinymce.models.HTMLField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TextImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('text', tinymce.models.HTMLField()),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TextItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('caption', tinymce.models.HTMLField()),
                ('text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='TopPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('css', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('js', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('templates', 'templates'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('top.html', 'top.html')], default='', max_length=255, null=True)),
                ('backgound', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('text', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('banner', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('free_delivery_button', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('no_delivery_button', models.ImageField(blank=True, default='', null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripleTextItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField()),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('subtext', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('css', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('js', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('templates', 'templates'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('top.html', 'top.html')], default='', max_length=255, null=True)),
                ('items', models.ManyToManyField(to='base.TextImageItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YellowPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('css', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('js', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('templates', 'templates'), ('templates.html', 'templates.html'), ('index.html', 'index.html'), ('top.html', 'top.html')], default='', max_length=255, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, default='', null=True)),
                ('items', models.ManyToManyField(to='base.TripleTextItem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='howpage',
            name='items',
            field=models.ManyToManyField(to='base.TextDoubleImageItem'),
        ),
        migrations.AddField(
            model_name='greenpage',
            name='items',
            field=models.ManyToManyField(to='base.TextImageItem'),
        ),
        migrations.AddField(
            model_name='forpage',
            name='items',
            field=models.ManyToManyField(to='base.ImageItem'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='items',
            field=models.ManyToManyField(to='base.TextItem'),
        ),
        migrations.AddField(
            model_name='factspage',
            name='items',
            field=models.ManyToManyField(to='base.TextImageItem'),
        ),
        migrations.AddField(
            model_name='docspage',
            name='items',
            field=models.ManyToManyField(to='base.ImageItem'),
        ),
    ]
