# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleTextDoubleImageItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('subimage', models.ImageField(upload_to='')),
                ('caption', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='docspage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('templates.html', 'templates.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('templates.html', 'templates.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('templates.html', 'templates.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('templates.html', 'templates.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('templates.html', 'templates.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='items',
            field=models.ManyToManyField(to='base.DoubleTextDoubleImageItem'),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('templates.html', 'templates.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('templates.html', 'templates.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('templates.html', 'templates.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('templates.html', 'templates.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('templates.html', 'templates.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('templates.html', 'templates.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html')], default='', max_length=255, null=True),
        ),
    ]
