# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factspage',
            name='free_delivery_button',
        ),
        migrations.RemoveField(
            model_name='factspage',
            name='no_delivery_button',
        ),
        migrations.AddField(
            model_name='textdoubleimageitem',
            name='subimage',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
