# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170226_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='docspage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factspage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqpage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forpage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='greenpage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='howpage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mintpage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orangepage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toppage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whypage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yellowpage',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docspage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='factspage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='forpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='greenpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='howpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mintpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orangepage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='whypage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='yellowpage',
            name='template',
            field=models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True),
        ),
    ]
