# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20170226_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('template', models.CharField(blank=True, choices=[('green.html', 'green.html'), ('bottom.html', 'bottom.html'), ('page_for.html', 'page_for.html'), ('blue.html', 'blue.html'), ('templates', 'templates'), ('yellow.html', 'yellow.html'), ('templates.html', 'templates.html'), ('footer.html', 'footer.html'), ('faq.html', 'faq.html'), ('facts.html', 'facts.html'), ('index.html', 'index.html'), ('docs.html', 'docs.html'), ('why.html', 'why.html'), ('mint.html', 'mint.html'), ('top.html', 'top.html'), ('orange.html', 'orange.html')], default='', max_length=255, null=True)),
                ('order', models.IntegerField()),
                ('free_delivery_button', models.ImageField(upload_to='')),
                ('no_delivery_button', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='docspage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='docspage',
            name='js',
        ),
        migrations.RemoveField(
            model_name='factspage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='factspage',
            name='js',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='js',
        ),
        migrations.RemoveField(
            model_name='forpage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='forpage',
            name='js',
        ),
        migrations.RemoveField(
            model_name='greenpage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='greenpage',
            name='js',
        ),
        migrations.RemoveField(
            model_name='howpage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='howpage',
            name='js',
        ),
        migrations.RemoveField(
            model_name='mintpage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='mintpage',
            name='js',
        ),
        migrations.RemoveField(
            model_name='orangepage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='orangepage',
            name='js',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.RemoveField(
            model_name='toppage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='toppage',
            name='js',
        ),
        migrations.RemoveField(
            model_name='whypage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='whypage',
            name='js',
        ),
        migrations.RemoveField(
            model_name='yellowpage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='yellowpage',
            name='js',
        ),
        migrations.RemoveField(
            model_name='yellowpage',
            name='text',
        ),
        migrations.AddField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
