# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 22:39
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_tripletextitem_yellowpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='yellowpage',
            name='text',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
